INSERT INTO CONTACT (NAME, EMAIL, TELEPHONE) VALUES ('Ana', 'ana@mail.com', '1111-1111');
INSERT INTO CONTACT (NAME, EMAIL, TELEPHONE) VALUES ('Bia', 'bia@mail.com', '2222-2222');
INSERT INTO CONTACT (NAME, EMAIL, TELEPHONE) VALUES ('Cris', 'cris@mail.com', '3333-3333');
